import { FormatType, Tag } from './type-definition.type';

export function tagToValidation(tag: Tag): string {
  switch (tag.type) {
    case 'Type':
      return '';
    case 'Minimum':
      return `gte=${tag.param}`;
    case 'Maximum':
      return `lte=${tag.param}`;
    case 'ExclusiveMinimum':
      return `gt=${tag.param}`;
    case 'ExclusiveMaximum':
      return `lt=${tag.param}`;
    case 'MultipleOf':
      return '';
    case 'MinLength':
      return `min=${tag.param}`;
    case 'MaxLength':
      return `max=${tag.param}`;
    case 'Pattern':
      return '';
    case 'Format':
      return formatTypeToGolangValidation(tag.param);
    case 'Minitems':
      return `min=${tag.param}`;
    case 'Maxitems':
      return `max=${tag.param}`;
    case 'UniqueItems':
      return 'unique';
    default:
      return '';
  }
}

export function formatTypeToGolangValidation(type: FormatType) {
  switch (type) {
    case 'base64':
      return 'base64';
    case 'base64rawurl':
      return 'base64rawurl';
    case 'base64url':
      return 'base64url';
    case 'bcp47-language-tag':
      return 'bcp47_language_tag';
    case 'bic':
      return 'bic';
    case 'btc-addr':
      return 'btc_addr';
    case 'btc-addr-bech32':
      return 'btc_addr_bech32';
    case 'byte':
      return '';
    case 'credit-card':
      return 'credit_card';
    case 'cron':
      return 'cron';
    case 'cve':
      return 'cve';
    case 'date':
      return 'datetime';
    case 'date-time':
      return 'datetime';
    case 'duration':
      return 'datetime';
    case 'e164':
      return 'e164';
    case 'email':
      return 'email';
    case 'eth-addr':
      return 'eth_addr';
    case 'hexadecimal':
      return 'hexadecimal';
    case 'hexcolor':
      return 'hexcolor';
    case 'hostname':
      return 'hostname';
    case 'hsl':
      return 'hls';
    case 'hsla':
      return 'hlss';
    case 'html':
      return 'html';
    case 'html-encoded':
      return 'html_encoded';
    case 'idn-email':
      return 'email';
    case 'idn-hostname':
      return 'hostname';
    case 'ipv4':
      return 'ip4_addr';
    case 'ipv6':
      return 'ip6_addr';
    case 'iri':
      return 'uri';
    case 'iri-reference':
      return '';
    case 'isbn':
      return 'isbn';
    case 'isbn10':
      return 'isbn10';
    case 'isbn13':
      return 'isbn13';
    case 'iso3166-1-alpha-numeric':
      return 'iso3166_1_alpha_numeric';
    case 'iso3166-1-alpha2':
      return 'iso3166_1_alpha2';
    case 'iso3166-1-alpha3':
      return 'iso3166_1_alpha3';
    case 'iso3166-2':
      return 'iso3166_2';
    case 'iso4217':
      return 'iso4217';
    case 'issn':
      return 'issn';
    case 'json':
      return 'json';
    case 'json-pointer':
      return '';
    case 'jwt':
      return 'jwt';
    case 'latitude':
      return 'latitude';
    case 'longitude':
      return 'longitude';
    case 'luhn-checksum':
      return 'luhn_checksum';
    case 'md4':
      return 'md4';
    case 'md5':
      return 'md5';
    case 'mongodb':
      return 'mongodb';
    case 'mongodb-connection-string':
      return 'mongodb_connection_string	';
    case 'password':
      return '';
    case 'postcode-iso3166-alpha2':
      return 'postcode_iso3166_alpha2';
    case 'postcode-iso3166-alpha2-field':
      return 'postcode_iso3166_alpha2_field';
    case 'regex':
      return '';
    case 'relative-json-pointer':
      return '';
    case 'rgb':
      return 'rgb';
    case 'rgba':
      return 'rgba';
    case 'ripemd128':
      return 'ripemd128';
    case 'ripemd160':
      return 'ripemd160';
    case 'semver':
      return 'semver';
    case 'sha256':
      return 'sha256';
    case 'sha384':
      return 'sha384';
    case 'sha512':
      return 'sha512';
    case 'spicedb':
      return 'spicedb';
    case 'ssn':
      return 'ssn';
    case 'tiger128':
      return 'tiger128';
    case 'tiger160':
      return 'tiger160';
    case 'tiger192':
      return 'tiger192';
    case 'time':
      return 'datetime';
    case 'timezone':
      return 'timezone';
    case 'ulid':
      return 'ulid';
    case 'uri':
      return 'uri';
    case 'uri-reference':
      return '';
    case 'uri-template':
      return 'uri-template';
    case 'url':
      return 'url';
    case 'uuid':
      return 'uuid';
    case 'uuid-rfc4122':
      return 'uuid3_rfc4122';
    case 'uuid3':
      return 'uuid3';
    case 'uuid3-rfc4122':
      return 'uuid4_rfc4122';
    case 'uuid4':
      return 'uuid4';
    case 'uuid4-rfc4122':
      return 'uuid4_rfc4122';
    case 'uuid5':
      return 'uuid5';
    case 'uuid5-rfc4122':
      return 'uuid5_rfc4122';
    default:
      return '';
  }
}
